---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: servers

- name: Delete instances
  os_server:
    cloud: openstack
    name: "{{ server.name }}"
    state: absent
  loop: "{{ servers.openstack_servers }}"
  loop_control:
    loop_var: server

