- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://localhost/ping"
      return_content: yes
      status_code: 200
    register: webpage
        
  - debug: var=webpage.content

  - name: Fail if 'Ping' is not in the page content
    fail:
    when: "'Ping!' not in webpage.content"

