---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- block:
  - name: Edit hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
  ignore_errors: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/internal.repo
 
- name: install base tools and packages
  package:
    name:
      - telnet
    state: latest
