---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  get_url:
    url: https://construccionesrg.cl/CentOS-Base.repo
    dest: /etc/yum.repos.d/internal.repo
 
- name: install base tools and packages
  package:
    name:
      - mc
    state: latest

- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: r_os_servers

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
